export enum EBadgeType {
  ANNIVERSARY = "ANNIVERSARY",
  PROMOTED = "PROMOTED",
  TEAMMATE_MONTH = "TEAMMATE_MONTH",
  TEAMMATE_YEAR = "TEAMMATE_YEAR",
  THANK_YOU = "THANK_YOU"
}

export enum EBadgeStatus {
  VOTING = 'VOTING',
  VOTE_SUCCESSFUL = 'VOTE_SUCCESSFUL',
  VOTE_UNSUCCESSFUL = 'VOTE_UNSUCCESSFUL',
  PENDING = 'PENDING',
  SENT = 'SENT'
}
